name: Build Raspberry Pi Images

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Raspberry Pi Images
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build project
        run: ./build.sh
      - name: Upload artifact (for release job only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: buildroot/output/images/

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: buildroot/output/images/sdcard.img
